### ISSUE TITLE
Pen up is not working well

### ISSUE THREAD

**Issue by kelalaka-153** [cavenel/ev3-print3rbot#3]
I've built according to design AFAIK. After calibration, it prints three warnings

impossible to fix position, attempt 1 on 10.
impossible to fix position, attempt 1 on 10.
impossible to fix position, attempt 1 on 10.

I think they are part of the calibration.

The first pen_up is fine. But after the pen_down the pen_up is not working. 
So, It draws everywhere.

Somehow, can we increase the pen up more. I couldn't fine a way.

Best

**Comment by cavenel** [comment]
The "impossible to fix position" message is completely normal. It is due to ev3dev drivers, you can not reset a moving motor (see https://github.com/ev3dev/ev3dev/issues/320) so when it tries to reset it for callibration, it tries until motor is completely stopped.
For the pen up problem, I think it is a question of length / vertical position of the pen, as well as calibration of how much you pull for upper position. You can fix that by tuning the pen_up function in writer.py, changing 40 to 50 or 60:

```
 self.mot_lift.goto_position(40, 30, regulate = 'off', stop_command='brake', wait = 1)
```

to

```
 self.mot_lift.goto_position(60, 30, regulate = 'off', stop_command='brake', wait = 1)
```

If only the first pen up is fine, it means that the position is switching. Maybe 40 is to big and the pen is blocked. You can then tune 40 to 30, or tune pen_down value from 14 to 20 or more?

**Comment by cavenel** [comment]
Please reopen the issue if you still have the problem. After 1 year I consider it solved.
